### ISSUE TITLE
Build issue - NARandom uses a definition that's not in NAChloride

### ISSUE THREAD

**Issue by ozobken** [gabriel/KBPGP#1]
KBJSCore.m has a call to an NARandom which has a definition requiring error:

(line 59) NSString *data = GHBase64StringFromNSData([NARandom randomData:[numBytes toUInt32] error:&error]);

as well as:

(line 110)  return [[NARandom randomData:numBytes error:nil] na_hexString];

(this one also gets grumpy about the NSData na_hexString too - but not so sure about that.)

The current release of NAChloride's NARandom only has:
- (NSData *)randomData:(NSUInteger)length;

..are we out of sync somewhere, or am I missing something I need?

**Comment by alexkunitsa** [comment]
Hi,
I had the same issue. As a temp solution:

added to NAChloride/NAChloride.h :

```
#import "NASecRandom.h"
#import "NANSData+Utils.h"
```

and replaced NARandom  with NASecRandom in KBJSCore.m

**Comment by ozobken** [comment]
Of course - I worked around it by just changing the calls in KBJSCore.m to use the version without *error :)

**Comment by gabriel** [comment]
Might be fixed but I'm having trouble updating the pod. You can try to point at head..

`pod 'KBPGP', :git => 'https://github.com/gabriel/KBPGP.git', :branch => :master`

**Comment by gabriel** [comment]
ok I pushed a new pod.. should be version 0.1.4

I had to do --use-libraries because of openssl.. e.g. `pod trunk push --use-libraries`

**Comment by ozobken** [comment]
Looks good

-> Installing KBPGP 0.1.3 (was 0.1.1)
