### ISSUE TITLE
Can't install with CocoaPods

### ISSUE THREAD

**Issue by alexkunitsa** [gabriel/KBPGP#2]
When I try to install, I have issue:

```
pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `KBPGP`
```

**Comment by ozobken** [comment]
Use:

  pod 'KBPGP', :git => 'https://github.com/gabriel/KBPGP.git'

and I've also found that some tasks fail with Mantle 2.0.3, so also:

  pod 'Mantle', '2.0.2'

**Comment by alexkunitsa** [comment]
thanks! that helped :)
